# Generated by Django 4.2 on 2023-05-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user_id',
            new_name='user_nickname',
        ),
    ]
