# Generated by Django 4.2 on 2023-05-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
