# Generated by Django 4.2 on 2023-06-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_bookmark_like_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='nickname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(null=True),
        ),
    ]
